# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10444cee699150be6e3ad0edacd0df36690633b823dbffadd1659897662e615104b29d32f2efc0f9e4213985bdd64e6dfe944cec732c4b7b322ea1b2dc88c72

test:
  secret_key_base: 8fd05418d73de6d549e866c699361dff7587eba625ffe044ff7231a252130c4ce29c9052d897fd1fa179c95bf7b8b3e9439f72dda0d3fcd094ab965e934e8404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
